CREATE TABLE dbPRODUTO (
	ID_PRODUTO INT IDENTITY(0,1) PRIMARY KEY NOT NULL,
	NOME VARCHAR(100),
	DESCRICAO VARCHAR(100) NOT NULL,
	UNIDADES INT NOT NULL,
	VALOR INT NOT NULL
);

CREATE TABLE dbVENDA (
	ID_VENDA INT IDENTITY(0,1) PRIMARY KEY NOT NULL,
	ID_PRODUTO INT NOT NULL,
	DATA_VENDA DATETIME NOT NULL,
	CONSTRAINT PK_dbPRODUTO 
        PRIMARY KEY (ID_PRODUTO)
);

CREATE TABLE dbCOMPRA (
	ID_COMPRA INT IDENTITY(0,1) PRIMARY KEY NOT NULL,
	ID_PRODUTO INT NOT NULL,
	DATA_COMPRA DATETIME NOT NULL,
	CONSTRAINT PK_dbPRODUTO
		PRIMARY KEY (ID_PRODUTO)
);

CREATE TABLE SALDO (
	ID_VENDA INT IDENTITY(0,1) PRIMARY KEY NOT NULL,
	QTD INT NOT NULL
);