CREATE TABLE dbPRODUTO (
	ID_PRODUTO INT IDENTITY(0,1) PRIMARY KEY NOT NULL,
	NOME VARCHAR(100),
	DESCRICAO VARCHAR(100) NOT NULL,
	UNIDADES INT NOT NULL,
	VALOR INT NOT NULL
);

CREATE TABLE dbVENDA (
	ID_VENDA INT IDENTITY(0,1) PRIMARY KEY NOT NULL,
	ID_PRODUTO INT NOT NULL,
	DATA_VENDA DATETIME NOT NULL,
	FOREIGN KEY (ID_PRODUTO) REFERENCES dbPRODUTO(ID_PRODUTO)
);

CREATE TABLE dbCOMPRA (
	ID_COMPRA INT IDENTITY(0,1) PRIMARY KEY NOT NULL,
	ID_PRODUTO INT NOT NULL,
	DATA_COMPRA DATETIME NOT NULL,
	FOREIGN KEY (ID_PRODUTO) REFERENCES dbPRODUTO(ID_PRODUTO)
);

CREATE TABLE SALDO (
	ID_SALDO INT IDENTITY(0,1) PRIMARY KEY NOT NULL,
	ID_VENDA INT NOT NULL,
	
	QTD INT NOT NULL
	FOREIGN KEY (ID_VENDA) REFERENCES dbVENDA(ID_VENDA)
	
);

UPDATE SALDO (
	NOME VARCHAR(100) NOT NULL,
	FOREIGN KEY (NOME) REFERENCES 
);

GO

CREATE PROCEDURE ClienteESaldo 
	@NOME VARCHAR(100),
	@DESCRICAO VARCHAR(100),
	@UNIDADES INT,
	@VALOR INT,
	@QTD INT

AS
BEGIN
	INSERT INTO dbPRODUTO
	(NOME, DESCRICAO, UNIDADES, VALOR)
	VALUES
	(@NOME, @DESCRICAO, @UNIDADES, @VALOR)
	INSERT INTO SALDO
	(QTD)
	VALUES

END
GO
