CREATE TABLE CAIXA
(
    DATA            DATETIME,
    SALDO_INICIAL   DECIMAL(10,2),
    SALDO_FINAL     DECIMAL(10,2)
)
GO

INSERT INTO CAIXA
VALUES (CONVERT(DATETIME, CONVERT(VARCHAR, GETDATE(), 103)), 100, 100)
GO

CREATE TABLE VENDAS
(
    DATA    DATETIME,
    CODIGO  INT,
    VALOR   DECIMAL(10,2)
)
GO

CREATE TRIGGER TGR_VENDAS_AI
ON VENDAS
FOR INSERT
AS
BEGIN
    DECLARE
    @VALOR  DECIMAL(10,2),
    @DATA   DATETIME

    SELECT @DATA = DATA, @VALOR = VALOR FROM INSERTED

    UPDATE CAIXA SET SALDO_FINAL = SALDO_FINAL + @VALOR
    WHERE DATA = @DATA
END
GO

INSERT INTO VENDAS
VALUES (CONVERT(DATETIME, CONVERT(VARCHAR, GETDATE(), 103)), 1, 10)

SELECT * FROM CAIXA

GO

CREATE TRIGGER TGR_VENDAS_AD
ON VENDAS
FOR DELETE
AS
BEGIN
    DECLARE
    @VALOR  DECIMAL(10,2),
    @DATA   DATETIME

    SELECT @DATA = DATA, @VALOR = VALOR FROM DELETED

    UPDATE CAIXA SET SALDO_FINAL = SALDO_FINAL - @VALOR
    WHERE DATA = @DATA
END
GO

DELETE FROM VENDAS WHERE CODIGO = 1
GO


/** COM IA **/

CREATE TABLE Clientx (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Nome NVARCHAR(100),
    Email NVARCHAR(100),
    DataCadastro DATETIME DEFAULT GETDATE()
);

CREATE TABLE LogClientes (
    IdLog INT PRIMARY KEY IDENTITY(1,1),
    IdCliente INT,
    Acao NVARCHAR(50),
    DataAcao DATETIME DEFAULT GETDATE()
);

GO

CREATE TRIGGER trg_AposInserirCliente
ON Clientx
AFTER INSERT
AS
BEGIN
    INSERT INTO LogClientes (IdCliente, Acao)
    SELECT Id, 'INSERT'
    FROM inserted;
END;

GO

INSERT INTO Clientx (Nome, Email)
VALUES ('João Silva', 'joao@email.com');

SELECT * FROM LogClientes;



